const router = require("./routes/plantForm/binding-organ");

const array = [
    {
        "create_by": null,
        "create_time": "None",
        "id": 1,
        "menu_name": "安全事件",
        "menu_type": "M",
        "order_num": 1,
        "parent_id": 0,
        "remark": null,
        "status": false,
        "update_by": null,
        "update_time": "None",
        "url": "incident"
    },
    {
        "create_by": null,
        "create_time": "None",
        "id": 2,
        "menu_name": "总体状态",
        "menu_type": "C",
        "order_num": 1,
        "parent_id": 1,
        "remark": null,
        "status": false,
        "update_by": null,
        "update_time": "None",
        "url": "total"
    },
    {
        "create_by": null,
        "create_time": "None",
        "id": 3,
        "menu_name": "网络攻击事件",
        "menu_type": "C",
        "order_num": 2,
        "parent_id": 1,
        "remark": null,
        "status": false,
        "update_by": null,
        "update_time": "None",
        "url": "cyber"
    },
    {
        "create_by": null,
        "create_time": "None",
        "id": 4,
        "menu_name": "恶意代码事件",
        "menu_type": "C",
        "order_num": 3,
        "parent_id": 1,
        "remark": null,
        "status": false,
        "update_by": null,
        "update_time": "None",
        "url": "malicious"
    },
    {
        "create_by": null,
        "create_time": "None",
        "id": 5,
        "menu_name": "威胁情报事件",
        "menu_type": "C",
        "order_num": 4,
        "parent_id": 1,
        "remark": null,
        "status": false,
        "update_by": null,
        "update_time": "None",
        "url": "threatIntelligence"
    },
    {
        "create_by": null,
        "create_time": "None",
        "id": 6,
        "menu_name": "恶意文件分析",
        "menu_type": "C",
        "order_num": 2,
        "parent_id": 0,
        "remark": null,
        "status": false,
        "update_by": null,
        "update_time": "None",
        "url": "maliciousFile"
    },
    {
        "create_by": null,
        "create_time": "None",
        "id": 7,
        "menu_name": "AI基因分析",
        "menu_type": "C",
        "order_num": 3,
        "parent_id": 0,
        "remark": null,
        "status": false,
        "update_by": null,
        "update_time": "None",
        "url": "aigene"
    },
    {
        "create_by": null,
        "create_time": "None",
        "id": 8,
        "menu_name": "策略配置",
        "menu_type": "M",
        "order_num": 4,
        "parent_id": 0,
        "remark": null,
        "status": false,
        "update_by": null,
        "update_time": "None",
        "url": "policy"
    },
    {
        "create_by": null,
        "create_time": "None",
        "id": 9,
        "menu_name": "流量还原配置",
        "menu_type": "M",
        "order_num": 1,
        "parent_id": 8,
        "remark": null,
        "status": false,
        "update_by": null,
        "update_time": "None",
        "url": "flowRestore"
    },
    {
        "create_by": null,
        "create_time": "None",
        "id": 10,
        "menu_name": "恶意检测配置",
        "menu_type": "M",
        "order_num": 2,
        "parent_id": 8,
        "remark": null,
        "status": false,
        "update_by": null,
        "update_time": "None",
        "url": "detection"
    },
    {
        "create_by": null,
        "create_time": "None",
        "id": 11,
        "menu_name": "流量还原配置修改",
        "menu_type": "F",
        "order_num": 1,
        "parent_id": 9,
        "remark": null,
        "status": false,
        "update_by": null,
        "update_time": "None",
        "url": null
    },
    {
        "create_by": null,
        "create_time": "None",
        "id": 12,
        "menu_name": "恶意检测配置修改",
        "menu_type": "F",
        "order_num": 1,
        "parent_id": 10,
        "remark": null,
        "status": false,
        "update_by": null,
        "update_time": "None",
        "url": null
    },
    {
        "create_by": null,
        "create_time": "None",
        "id": 13,
        "menu_name": "APT样本家族识别",
        "menu_type": "C",
        "order_num": 5,
        "parent_id": 0,
        "remark": null,
        "status": false,
        "update_by": null,
        "update_time": "None",
        "url": null
    },
    {
        "create_by": null,
        "create_time": "None",
        "id": 14,
        "menu_name": "系统配置",
        "menu_type": "M",
        "order_num": 6,
        "parent_id": 0,
        "remark": null,
        "status": false,
        "update_by": null,
        "update_time": "None",
        "url": null
    },
    {
        "create_by": null,
        "create_time": "None",
        "id": 15,
        "menu_name": "时间配置",
        "menu_type": "C",
        "order_num": 1,
        "parent_id": 14,
        "remark": null,
        "status": false,
        "update_by": null,
        "update_time": "None",
        "url": null
    },
    {
        "create_by": null,
        "create_time": "None",
        "id": 16,
        "menu_name": "时间修改",
        "menu_type": "F",
        "order_num": 1,
        "parent_id": 15,
        "remark": null,
        "status": false,
        "update_by": null,
        "update_time": "None",
        "url": null
    },
    {
        "create_by": null,
        "create_time": "None",
        "id": 17,
        "menu_name": "客户机列表",
        "menu_type": "C",
        "order_num": 2,
        "parent_id": 14,
        "remark": null,
        "status": false,
        "update_by": null,
        "update_time": "None",
        "url": null
    },
    {
        "create_by": null,
        "create_time": "None",
        "id": 18,
        "menu_name": "告警规则配置",
        "menu_type": "C",
        "order_num": 3,
        "parent_id": 14,
        "remark": null,
        "status": false,
        "update_by": null,
        "update_time": "None",
        "url": null
    },
    {
        "create_by": null,
        "create_time": "None",
        "id": 19,
        "menu_name": "告警规则上传",
        "menu_type": "F",
        "order_num": 1,
        "parent_id": 18,
        "remark": null,
        "status": false,
        "update_by": null,
        "update_time": "None",
        "url": null
    },
    {
        "create_by": null,
        "create_time": "None",
        "id": 20,
        "menu_name": "关于基因分析系统",
        "menu_type": "C",
        "order_num": 4,
        "parent_id": 14,
        "remark": null,
        "status": false,
        "update_by": null,
        "update_time": "None",
        "url": null
    },
    {
        "create_by": null,
        "create_time": "None",
        "id": 21,
        "menu_name": "审计日志",
        "menu_type": "M",
        "order_num": 7,
        "parent_id": 0,
        "remark": null,
        "status": false,
        "update_by": null,
        "update_time": "None",
        "url": null
    },
    {
        "create_by": null,
        "create_time": "None",
        "id": 22,
        "menu_name": "登录日志",
        "menu_type": "C",
        "order_num": 1,
        "parent_id": 21,
        "remark": null,
        "status": false,
        "update_by": null,
        "update_time": "None",
        "url": null
    },
    {
        "create_by": null,
        "create_time": "None",
        "id": 23,
        "menu_name": "登录日志导出",
        "menu_type": "F",
        "order_num": 1,
        "parent_id": 22,
        "remark": "",
        "status": false,
        "update_by": null,
        "update_time": "None",
        "url": null
    },
    {
        "create_by": null,
        "create_time": "None",
        "id": 24,
        "menu_name": "操作日志",
        "menu_type": "C",
        "order_num": 2,
        "parent_id": 21,
        "remark": null,
        "status": false,
        "update_by": null,
        "update_time": "None",
        "url": null
    },
    {
        "create_by": null,
        "create_time": "None",
        "id": 25,
        "menu_name": "操作日志导出",
        "menu_type": "F",
        "order_num": 1,
        "parent_id": 24,
        "remark": null,
        "status": false,
        "update_by": null,
        "update_time": "None",
        "url": null
    },
    {
        "create_by": null,
        "create_time": "None",
        "id": 27,
        "menu_name": "配置日志",
        "menu_type": "C",
        "order_num": 3,
        "parent_id": 21,
        "remark": null,
        "status": false,
        "update_by": null,
        "update_time": "None",
        "url": null
    },
    {
        "create_by": null,
        "create_time": "None",
        "id": 28,
        "menu_name": "配置日志导出",
        "menu_type": "F",
        "order_num": 1,
        "parent_id": 27,
        "remark": null,
        "status": false,
        "update_by": null,
        "update_time": "None",
        "url": null
    },
    {
        "create_by": null,
        "create_time": "None",
        "id": 30,
        "menu_name": "用户日志",
        "menu_type": "C",
        "order_num": 4,
        "parent_id": 21,
        "remark": null,
        "status": false,
        "update_by": null,
        "update_time": "None",
        "url": null
    },
    {
        "create_by": null,
        "create_time": "None",
        "id": 31,
        "menu_name": "用户日志导出",
        "menu_type": "F",
        "order_num": 1,
        "parent_id": 30,
        "remark": null,
        "status": false,
        "update_by": null,
        "update_time": "None",
        "url": null
    },
    {
        "create_by": null,
        "create_time": "None",
        "id": 32,
        "menu_name": "用户配置",
        "menu_type": "M",
        "order_num": 8,
        "parent_id": 0,
        "remark": null,
        "status": false,
        "update_by": null,
        "update_time": "None",
        "url": null
    },
    {
        "create_by": null,
        "create_time": "None",
        "id": 33,
        "menu_name": "用户管理",
        "menu_type": "C",
        "order_num": 1,
        "parent_id": 32,
        "remark": null,
        "status": false,
        "update_by": null,
        "update_time": "None",
        "url": null
    },
    {
        "create_by": null,
        "create_time": "None",
        "id": 34,
        "menu_name": "用户新增",
        "menu_type": "F",
        "order_num": 1,
        "parent_id": 33,
        "remark": null,
        "status": false,
        "update_by": null,
        "update_time": "None",
        "url": null
    },
    {
        "create_by": null,
        "create_time": "None",
        "id": 35,
        "menu_name": "用户删除",
        "menu_type": "F",
        "order_num": 2,
        "parent_id": 33,
        "remark": null,
        "status": false,
        "update_by": null,
        "update_time": "None",
        "url": null
    },
    {
        "create_by": null,
        "create_time": "None",
        "id": 36,
        "menu_name": "用户修改",
        "menu_type": "F",
        "order_num": 3,
        "parent_id": 33,
        "remark": null,
        "status": false,
        "update_by": null,
        "update_time": "None",
        "url": null
    },
    {
        "create_by": null,
        "create_time": "None",
        "id": 37,
        "menu_name": "用户查询",
        "menu_type": "F",
        "order_num": 4,
        "parent_id": 33,
        "remark": null,
        "status": false,
        "update_by": null,
        "update_time": "None",
        "url": null
    },
    {
        "create_by": null,
        "create_time": "None",
        "id": 38,
        "menu_name": "用户导出",
        "menu_type": "F",
        "order_num": 5,
        "parent_id": 33,
        "remark": null,
        "status": false,
        "update_by": null,
        "update_time": "None",
        "url": null
    },
    {
        "create_by": null,
        "create_time": "None",
        "id": 39,
        "menu_name": "重置密码",
        "menu_type": "F",
        "order_num": 6,
        "parent_id": 33,
        "remark": null,
        "status": false,
        "update_by": null,
        "update_time": "None",
        "url": null
    },
    {
        "create_by": null,
        "create_time": "None",
        "id": 40,
        "menu_name": "角色管理",
        "menu_type": "C",
        "order_num": 2,
        "parent_id": 32,
        "remark": null,
        "status": false,
        "update_by": null,
        "update_time": "None",
        "url": null
    },
    {
        "create_by": null,
        "create_time": "None",
        "id": 41,
        "menu_name": "角色新增",
        "menu_type": "F",
        "order_num": 1,
        "parent_id": 40,
        "remark": null,
        "status": false,
        "update_by": null,
        "update_time": "None",
        "url": null
    },
    {
        "create_by": null,
        "create_time": "None",
        "id": 42,
        "menu_name": "角色删除",
        "menu_type": "F",
        "order_num": 2,
        "parent_id": 40,
        "remark": null,
        "status": false,
        "update_by": null,
        "update_time": "None",
        "url": null
    },
    {
        "create_by": null,
        "create_time": "None",
        "id": 43,
        "menu_name": "角色修改",
        "menu_type": "F",
        "order_num": 3,
        "parent_id": 40,
        "remark": null,
        "status": false,
        "update_by": null,
        "update_time": "None",
        "url": null
    },
    {
        "create_by": null,
        "create_time": "None",
        "id": 44,
        "menu_name": "角色查询",
        "menu_type": "F",
        "order_num": 4,
        "parent_id": 40,
        "remark": null,
        "status": false,
        "update_by": null,
        "update_time": "None",
        "url": null
    },
    {
        "create_by": null,
        "create_time": "None",
        "id": 45,
        "menu_name": "角色导出",
        "menu_type": "F",
        "order_num": 5,
        "parent_id": 40,
        "remark": null,
        "status": false,
        "update_by": null,
        "update_time": "None",
        "url": null
    },
    {
        "create_by": null,
        "create_time": "None",
        "id": 46,
        "menu_name": "菜单管理",
        "menu_type": "C",
        "order_num": 3,
        "parent_id": 32,
        "remark": null,
        "status": false,
        "update_by": null,
        "update_time": "None",
        "url": null
    },
    {
        "create_by": null,
        "create_time": "None",
        "id": 47,
        "menu_name": "菜单新增",
        "menu_type": "F",
        "order_num": 1,
        "parent_id": 46,
        "remark": null,
        "status": false,
        "update_by": null,
        "update_time": "None",
        "url": null
    },
    {
        "create_by": null,
        "create_time": "None",
        "id": 48,
        "menu_name": "菜单删除",
        "menu_type": "F",
        "order_num": 2,
        "parent_id": 47,
        "remark": null,
        "status": false,
        "update_by": null,
        "update_time": "None",
        "url": null
    },
    {
        "create_by": null,
        "create_time": "None",
        "id": 49,
        "menu_name": "菜单修改",
        "menu_type": "F",
        "order_num": 3,
        "parent_id": 48,
        "remark": "",
        "status": false,
        "update_by": null,
        "update_time": "None",
        "url": null
    },
    {
        "create_by": null,
        "create_time": "None",
        "id": 50,
        "menu_name": "菜单查询",
        "menu_type": "F",
        "order_num": 4,
        "parent_id": 49,
        "remark": null,
        "status": false,
        "update_by": null,
        "update_time": "None",
        "url": null
    }
];
const routerA = [];
array.map((e, i) => {
    if (e.menu_type === 'M') {
        routerA.push({
            path: `/${e.url}`,
            name: e.menu_name,
            meta: { title: e.menu_name, icon: 'shield' },

          });
        
    }
});
console.log(routerA);